name: Publish Python Package

on:
  push:
    tags:
      - "v*.*.*"  # Triggers the workflow on version tags, e.g., v1.0.0, v2.1.3

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Set your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine  # For packaging and publishing

      - name: Build package
        run: python -m build

      - name: Publish package to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          python -m twine upload dist/*
